version: 2.1

commands:

  pip_dev_install:
    description: "Install beanmachine[dev] & dependencies via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install numpy"
          command: sudo pip install --progress-bar off numpy
      - run:
          name: "Install pytorch"
          command: sudo pip install --progress-bar off torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: "Install beanmachine[dev]"
          command: sudo pip install -v -e .[dev]

  pip_lint_install:
    description: "Install beanmachine[lint] & dependencies via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install lint packages"
          command: sudo pip install --progress-bar off black==19.3b0 isort flake8

  lint_flake8:
    description: "Lint with flake8"
    steps:
      - run:
          name: "Lint with flake8"
          command: flake8

  lint_isort:
    description: "Lint with isort"
    steps:
      - run:
          name: "Lint with isort"
          command: >
            isort --check-only --diff --line-width=88 --multi-line=3
            --trailing-comma --force-grid-wrap=0 --section-default=THIRDPARTY
            --lines-after-imports=2 --combine-as

  lint_black:
    description: "Lint with black"
    steps:
      - run:
          name: "Lint with black"
          command: black --check --diff --line-length=88 .

  unit_tests:
    description: "Run unit tests"
    steps:
      - run:
          name: "Run unit tests"
          command: pytest -ra --cov=. --cov-report term-missing


jobs:

  test_py36_pip:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - pip_dev_install
      - unit_tests

  lint_py36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - pip_lint_install
      - lint_flake8
      - lint_isort
      - lint_black


aliases:

  - &exclude_ghpages_fbconfig
    branches:
      ignore:
        - gh-pages
        - fb-config


workflows:

  lint_and_test:
    jobs:
      - lint_py36:
          filters: *exclude_ghpages_fbconfig

      - test_py36_pip:
          filters: *exclude_ghpages_fbconfig
