version: 2.1

commands:

  pip_install_deps:
    description: "Install beanmachine dependencies via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install numpy"
          command: sudo pip install --progress-bar off numpy
      - run:
          name: "Install pytorch"
          command: sudo pip install --progress-bar off torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

  dev_install:
    description: "Install beanmachine[dev] in editable mode via pip"
    steps:
      - run:
          name: "Install beanmachine[dev]"
          command: sudo pip install --progress-bar off -v -e .[dev]

  user_install:
    description: "Install beanmachine as an ordinary user would via pip"
    steps:
      - run:
          name: "Install beanmachine"
          command: sudo pip install --progress-bar off -v .

  apt_get_install_deps:
    description: "Install beanmachine graph dependencies via apt-get"
    steps:
      - run:
          name: "Update package lists"
          command: sudo apt-get update
      - run:
          name: "Install Boost, Eigen, and PyBind11"
          command: sudo apt-get install libboost-dev libeigen3-dev pybind11-dev

  pip_lint_install:
    description: "Install lint packages via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install lint packages"
          command: sudo pip install --progress-bar off black==19.3b0 isort==4.3.21 flake8

  lint_flake8:
    description: "Lint with flake8"
    steps:
      - run:
          name: "Lint with flake8"
          command: flake8

  lint_isort:
    description: "Lint with isort"
    steps:
      - run:
          name: "Lint with isort"
          command: >
            isort --check-only --diff --line-width=88 --multi-line=3
            --trailing-comma --force-grid-wrap=0 --section-default=THIRDPARTY
            --lines-after-imports=2 --combine-as

  lint_black:
    description: "Lint with black"
    steps:
      - run:
          name: "Lint with black"
          command: black --check --diff --line-length=88 .

  dev_unit_tests:
    description: "Run unit tests when installed in dev mode"
    steps:
      - run:
          name: "Run unit tests"
          command: pytest --cov=. --cov-report term-missing

  user_par_unit_tests:
    description: "Run unit tests in parallel as an ordinary user"
    steps:
      - run:
          name: "Install test dependencies"
          command: pip install pytest gpytorch pytest-xdist
      - run:
          name: "Run unit tests in parallel"
          command: pytest -n 20 -vv

  nightly_tests:
    description: "Run nightly tests as an ordinary user"
    steps:
      - run:
          name: "Install test dependencies"
          command: pip install pytest gpytorch pytest-xdist
      - run:
          name: "Run nightly tests and report overall runtimes"
          command: pytest -n auto -o python_files="*_nightly.py" --durations=0


jobs:

  dev_install_test_py37_pip:
    docker:
      - image: circleci/python:3.7
    steps:
      - apt_get_install_deps
      - pip_install_deps
      - checkout
      - dev_install
      - dev_unit_tests

  user_par_install_test_py37_pip:
    docker:
      - image: circleci/python:3.7
    steps:
      - apt_get_install_deps
      - pip_install_deps
      - checkout
      - user_install
      - user_par_unit_tests

  lint_py37_pip:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - pip_lint_install
      - lint_flake8
      - lint_isort
      - lint_black

  nightly_test_py37_pip:
    docker:
      - image: circleci/python:3.7
    steps:
      - apt_get_install_deps
      - pip_install_deps
      - checkout
      - user_install
      - nightly_tests


aliases:

  - &exclude_ghpages_fbconfig
    branches:
      ignore:
        - gh-pages
        - fb-config


workflows:

  lint_and_test:
    jobs:
      - lint_py37_pip:
          filters: *exclude_ghpages_fbconfig

      - dev_install_test_py37_pip:
          filters: *exclude_ghpages_fbconfig

      - user_par_install_test_py37_pip:
          filters: *exclude_ghpages_fbconfig

  nightly_test:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly_test_py37_pip
