version: 2.1

commands:

  pip_install_deps:
    description: "Install beanmachine dependencies via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install numpy"
          command: sudo pip install --progress-bar off numpy
      - run:
          name: "Install pytorch"
          command: sudo pip install --progress-bar off torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

  pip_dev_install:
    description: "Install beanmachine[dev] via pip"
    steps:
      - run:
          name: "Install beanmachine[dev]"
          command: sudo pip install -v -e .[dev]

  apt_get_install_deps:
    description: "Install beanmachine graph dependencies via apt-get"
    steps:
      - run:
          name: "Update package lists"
          command: sudo apt-get update
      - run:
          name: "Install Boost"
          command: sudo apt-get install libboost-all-dev
      - run:
          name: "Install Eigen"
          command: sudo apt-get install libeigen3-dev

  setup_py_install:
    description: "Install beanmachine as an ordinary user would via setup.py install"
    steps:
      - run:
          name: "Install beanmachine"
          command: sudo python setup.py install

  pip_lint_install:
    description: "Install lint packages via pip"
    steps:
      - run:
          name: "Upgrade pip"
          command: sudo pip install --progress-bar off --upgrade pip
      - run:
          name: "Install lint packages"
          command: sudo pip install --progress-bar off black==19.3b0 isort==4.3.21 flake8

  lint_flake8:
    description: "Lint with flake8"
    steps:
      - run:
          name: "Lint with flake8"
          command: flake8

  lint_isort:
    description: "Lint with isort"
    steps:
      - run:
          name: "Lint with isort"
          command: >
            isort --check-only --diff --line-width=88 --multi-line=3
            --trailing-comma --force-grid-wrap=0 --section-default=THIRDPARTY
            --lines-after-imports=2 --combine-as

  lint_black:
    description: "Lint with black"
    steps:
      - run:
          name: "Lint with black"
          command: black --check --diff --line-length=88 .

  dev_unit_tests:
    description: "Run unit tests when installed in dev mode"
    steps:
      - run:
          name: "Run unit tests"
          command: pytest -ra --cov=. --cov-report term-missing

  user_unit_tests:
    description: "Run unit tests when as an ordinary user would"
    steps:
      - run:
          name: "Install pytest"
          command: pip install pytest
      - run:
          name: "Run unit tests"
          command: pytest --pyargs beanmachine


jobs:

  dev_install_test_py36_pip:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - pip_install_deps
      - apt_get_install_deps
      - pip_dev_install
      - dev_unit_tests

  user_install_test_py36_pip:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - pip_install_deps
      - apt_get_install_deps
      - setup_py_install
      - user_unit_tests

  lint_py36_pip:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - pip_lint_install
      - lint_flake8
      - lint_isort
      - lint_black


aliases:

  - &exclude_ghpages_fbconfig
    branches:
      ignore:
        - gh-pages
        - fb-config


workflows:

  lint_and_test:
    jobs:
      - lint_py36_pip:
          filters: *exclude_ghpages_fbconfig

      - dev_install_test_py36_pip:
          filters: *exclude_ghpages_fbconfig

      - user_install_test_py36_pip:
          filters: *exclude_ghpages_fbconfig
