/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

module.exports = {
  someSidebar: {
    Overview: [
      'overview/introduction/introduction',
      'overview/quick_start/quick_start',
      'overview/modeling/modeling',
      'overview/inference/inference',
      'overview/analysis/analysis',
    ],
    Tutorials: ['overview/tutorials/tutorials'],
    Packages: ['overview/packages/packages'],
    Framework: [
      'framework_topics/inference/inference', // Throwing this at top, even though it's embedded below, because I believe it belongs up here (??)
      {
        // This whole section needs to be edited (heavily) and probably organized formally, rather than auto-generated
        type: 'autogenerated',
        dirName: 'framework_topics', // '.' means the current docs folder
      },
    ],
    API: [], // #TODO: Brian Johnson will populate this!
    Advanced: ['overview/bmg/bmg', 'overview/beanstalk/beanstalk'],
    Contributing: ['contributing'],
    'Sitemap (formerly TOC)': ['toc'], // Once everyone is used to this being here, we'll remove the "(formerly TOC)" part
  },
};
