;; ASCII ;;
; W: wall, D: door, k: key, g: gem, G: goal-gem, s: start, .: empty
; WW.W.W.WW
; WW.WGW.WW
; WW.WDW.WW
; WW.....WW
; sWgWWW.D.
; .WWWkWWW.
; .........
; WWWW.WWWW
; WWWk.gWWW
(define (problem doors-keys-gems-6)
  (:domain doors-keys-gems)
  (:objects up down left right - direction
            key1 key2 - key
            gem1 gem2 gem3 - gem)
  (:init (= (xdiff up) 0) (= (ydiff up) 1)
         (= (xdiff down) 0) (= (ydiff down) -1)
         (= (xdiff right) 1) (= (ydiff right) 0)
         (= (xdiff left) -1) (= (ydiff left) 0)
         (= (width) 9) (= (height) 9) (= (xpos) 1) (= (ypos) 5)
         (wall 1 1)
         (wall 2 1)
         (wall 3 1)
         (at key1 4 1)
         (itemloc 4 1)
         (at gem1 6 1)
         (itemloc 6 1)
         (wall 7 1)
         (wall 8 1)
         (wall 9 1)
         (wall 1 2)
         (wall 2 2)
         (wall 3 2)
         (wall 4 2)
         (wall 6 2)
         (wall 7 2)
         (wall 8 2)
         (wall 9 2)
         (wall 2 4)
         (wall 3 4)
         (wall 4 4)
         (at key2 5 4)
         (itemloc 5 4)
         (wall 6 4)
         (wall 7 4)
         (wall 8 4)
         (wall 2 5)
         (at gem2 3 5)
         (itemloc 3 5)
         (wall 4 5)
         (wall 5 5)
         (wall 6 5)
         (door 8 5)
         (doorloc 8 5)
         (wall 1 6)
         (wall 2 6)
         (wall 8 6)
         (wall 9 6)
         (wall 1 7)
         (wall 2 7)
         (wall 4 7)
         (door 5 7)
         (doorloc 5 7)
         (wall 6 7)
         (wall 8 7)
         (wall 9 7)
         (wall 1 8)
         (wall 2 8)
         (wall 4 8)
         (at gem3 5 8)
         (itemloc 5 8)
         (wall 6 8)
         (wall 8 8)
         (wall 9 8)
         (wall 1 9)
         (wall 2 9)
         (wall 4 9)
         (wall 6 9)
         (wall 8 9)
         (wall 9 9))
  (:goal (has gem3))
)
